ksis:
  - id: "KSI-001"
    name: "FIPS-validated encryption"
    description: "Ensure encryption for data at rest and in transit is FIPS-compliant"
    evidenceType: "Terraform Compliance Check"
    frequency: "Continuous"
  - id: "KSI-002"
    name: "MFA Enabled for all users"
    description: "Ensure IAM policies enforce MFA for access."
    evidenceType: "AWS IAM Policy Check"
    frequency: "Daily"
  - id: "KSI-003"
    name: "TLS 1.3 enforced on all endpoints"
    description: "Validate HTTPS configurations in ALBs, API Gateways."
    evidenceType: "AWS Config rules"
    frequency: "Continuous"
  - id: "KSI-004"
    name: "Encryption at Rest (Backups, Databases)"
    description: "Ensure all RDS, S3, Blob storage, and backups use encryption."
    evidenceType: "Terraform Compliance Check"
    frequency: "Continuous"
